### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'then')

### ISSUE THREAD

**Issue by jasonwmatteson** [TaTo30/VuePDF#44]
I have the following code:

```
<script setup lang="ts">
import { ref } from 'vue';
// @ts-ignore
// no type definitions found
import { VuePDF, usePDF } from '@tato30/vue-pdf';

const pdf = ref();

const getPdf = () => {
  const pdfInfo = usePDF('valid-path-to-a-pdf-file');

  if (pdfInfo.pdf) {
    pdf.value = pdf;
    console.log(pdfInfo);
  }

};
</script>
<template>
  <button @click="getPdf">Get PDF</button>
  <VuePDF :pdf="pdf" v-if="pdf" />
</template>
```

I get the following error when I click the button:

```
index.mjs:499 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'then')
    at O (index.mjs:499:17)
    at index.mjs:508:27
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:164:21)
    at hook.__weh.hook.__weh (runtime-core.esm-bundler.js:2685:29)
    at flushPostFlushCbs (runtime-core.esm-bundler.js:356:32)
    at flushJobs (runtime-core.esm-bundler.js:401:9)
```
I know the file exists and can be opened fine in Chrome and Acrobat. It is 91.4 MB in size.  I also get information in the pdfInfo object. (e.g. I can see the number of pages, the meta data, etc...)

**Comment by rxw1** [comment]
Hello good sir,

try it like this:

```vue
<script setup lang="ts">
import { ref } from 'vue';
import { VuePDF, usePDF } from '@tato30/vue-pdf';
const pdf = ref();
const getPdf = () => {
  pdf.value = usePDF('/what.pdf');
};
</script>
<template>
  <button @click="getPdf">Get PDF</button>
  <VuePDF :pdf="pdf.pdf" v-if="pdf" />
</template>```

Hope that helps.

**Comment by jasonwmatteson** [comment]
I decided to use a the vue3-pdf-app library instead.
